[package]
name = "runwell"
version = "0.1.0"
authors = ["Robin Freyler <robin.freyler@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmparser = "0.44"
thiserror = "1.0"
slice-of-array = "0.2.1"
derive_more = "0.99.2"

[features]
bench = []
